### ISSUE TITLE
The screen sharing function does not support Wayland

### ISSUE THREAD

**Issue by rich-purnell** [flathub/com.tencent.wemeet#16]
The Wayland protocol is the trend, please fully support the Wayland protocol.

**Comment by Mooling0602** [comment]
Tencent doesn't support Wayland for WeMeet, and please see this:
```
NOTE: This wrapper is not verified by, affiliated with, or supported by Tencent, inc.
```

**Comment by ztelliot** [comment]
I've found a new project that might solve the problem.

[https://github.com/xuwd1/wemeet-wayland-screenshare](https://github.com/xuwd1/wemeet-wayland-screenshare)

**Comment by szw0407** [comment]
Is it possible to embed the `wemeet-wayland-screenshare` project into this flatpak package? That will make it useable in DE or WMs including GNOME, KDE and Hyprland, which support `xdg-desktop-portal`.
