### ISSUE TITLE
fix pipewire sound problem

### ISSUE THREAD

**Issue by TSc2end** [flathub/com.tencent.wemeet#4]
你好，我发现程序在pipewire下声音有问题，参考[AUR的修复脚本](https://aur.archlinux.org/cgit/aur.git/tree/wemeet.sh?h=wemeet-bin)可知需要配置一个系统变量：PULSE_LATENCY_MSEC=20
我的修复方法：安装好包后，执行`sudo flatpak override --env=PULSE_LATENCY_MSEC=20 com.tencent.wemeet`追加变量。
是否可以像AUR包那样添加相关判断脚本进行修复？

**Comment by suokunlong** [comment]
I encountered the sound problem when I installed WeMeet on Fedora 36. It works OK in Fedora 35. It should be a pipwire issue as Fedora defaulted to pipewire.

**Comment by nuzar** [comment]
在 3.12.0.400 中解决了

https://aur.archlinux.org/cgit/aur.git/commit/wemeet.sh?h=wemeet-bin&id=becfec588411ea0d950759e1034d8382aec1d170
